version: '3.9'
services:
  database:
    image: mysql:8.0.28-oracle
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Tilog
      - MYSQL_USER=tilog
      - MYSQL_PASSWORD=tilog
    volumes:
      - "./mysql/mysql-init-files/:/docker-entrypoint-initdb.d/"
      - "./mysql/mysql-data:/var/lib/mysql"
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - tilog
networks:
  tilog:
    name: tilogNetwork
    driver: bridge
